### PR TITLE
update-xml-catalog: Ensure resulting file has proper SELinux context

### PR DESCRIPTION
**Pull request by jsegitz**

### CODE REVIEW

**Review by fsundermeyer — APPROVED** [review]
LGTM

**Comment by fsundermeyer** [comment]
@tomschr Can you please make sure to update the package?

**Comment by tomschr** [comment]
Thanks @jsegitz for your contribution! :+1:

**Comment by tomschr** [comment]
@fsundermeyer 
> Can you please make sure to update the package?

https://build.opensuse.org/request/show/964908

You can find it in [Publishing/sgml-skel](https://build.opensuse.org/package/show/Publishing/sgml-skel).

**Pull request merged**
